name: Validate With UV and Ruff

on:
  push:
  pull_request:

jobs:
  hacs:
    name: HACS Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v
      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands"
  validate_hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate
        uses: home-assistant/actions/hassfest@master
  validate_ruff:
    name: Test + advice with ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: latest
      - name: Install Ruff using uv
        run: uv pip install ruff
      - name: Lint critical errors with ruff
        run: |
          ruff check . --count --select E9,F63,F7,F82 --show-source --statistics
      - name: Don't mind these (less strict)
        run: |
          ruff check . --count --exit-zero --max-complexity 15 --line-length 90 --statistics --select I,P,WPS305,C812,E203,W503,E800
      - name: Docstrings
        run: |
          ruff check . --count --exit-zero --max-complexity 15 --line-length 90 --statistics --select D,DAR
      - name: Unused code warnings
        run: |
          echo "Some stuff may not be used, but is used in commented out code."
          echo "Make sure you check with the find command before you remove anything!"
          ruff check . --count --exit-zero --max-complexity 15 --line-length 90 --statistics --select F
          echo "Some stuff may not be used, but is used in commented out code."
          echo "Make sure you check with the find command before you remove anything!"
      - name: General stats, ignoring specific codes
        run: |
          ruff check . --count --exit-zero --max-complexity 15 --line-length 90 --statistics --ignore I,P,WPS305,C812,E203,W503,E800,D,DAR,F